version: "3"

services:
  # financeiro-alffa:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: financeiro-alffa    
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres
    volumes:
      - /tmp/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "ipec2024"
      POSTGRESS_USER: "ipec"
      POSTGRESS_DB: "financeiro"
      
    ports:
      - "5432:5432"    
 # sudo docker run -p 5432:5432 -v /tmp/database:/var/lib/postgresql/data -e POSTGRES_PASSWORD=ipec2024 -e POSTGRESS_USER=ipec -e POSTGRESS_DB=financeiro -d postgres
